#$schema: https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-project-1-frontend
  annotations:
    github.com/project-slug: djajcevic-idp/demo-project-1-frontend-acs
    backstage.io/environment: dev
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=demo-project-1-frontend'
    argocd/app-name: demo-project-1
    sonarqube.org/project-key: default/demo-project-1-frontend
    backstage.io/techdocs-ref: 'dir:.'
    demo.backstage.io/techdocs-builder: 'local'
  tags:
    - react
    - js
  links:
    - url: https://demo-project-1.apps.idp.dhl.com
      title: Website
      icon: star
spec:
  type: website
  lifecycle: development
  owner: demo-team
  system: demo
  dependsOn:
    - component:default/demo-project-1